## YAML Template.
---
language: php
php:
  - "5.5"
  - "5.6"

env:
  - DB=mysql

service:
  - memcached

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS lico;" -uroot; fi

install:
  - composer self-update
  - composer install
  - composer update

script: phpunit -c app/phpunit.travis.xml

