## YAML Template.
---
language: php
php:
  - "5.5"
  - "5.6"

env:
  - DB=mysql

service:
  - memcached

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS lico;" -uroot; fi

install:
  - composer self-update
  - composer install
  - composer update

script:
  - mkdir -p app/cache
  - mkdir -p app/logs
  - php app/console cache:clear
  - php app/console assets:install --symlink web
  - php app/console assetic:dump
  - phpunit -c app/phpunit.travis.xml

after_script:
  - php vendor/bin/coveralls
