## YAML Template.
---
language: php
php:
  - "5.6"

env:
  - DB=mysql

service:
  - memcached

install:
  - composer self-update
  - composer install
  - composer update

before_script:
  - mkdir -p app/cache
  - mkdir -p app/logs
  - php app/console doctrine:database:create
  - if [[ "$DB" == "mysql" ]]; then cd app/config/travis-sql; for i in *; do mysql -uroot licotest < ${i}; done; cd ../../..; fi
  - php app/console doctrine:cache:clear-metadata
  - php app/console cache:clear
  - php app/console assets:install --symlink web
  - php app/console assetic:dump
  - php app/console asm:translations:dummy
  - php app/console syw:user:create tester1 tester1@linuxcounter.net test123 en
  - php app/console syw:user:create tester2 tester2@linuxcounter.net test123 de

script:
  - phpunit -c app/phpunit.travis.xml

after_script:
  - php bin/coveralls
