## YAML Template.
---
language: php
php:
  - "5.5"
  - "5.6"

env:
  - DB=mysql

service:
  - memcached

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS lico;" -uroot; fi

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar update

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit -c app

