## YAML Template.
---
language: php
php:
  - "5.5"
  - "5.6"

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

service:
  - memcached

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS lico;" -uroot; fi

# install dependencies with composer
install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar update

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit -c app

# configure notifications (email, IRC, campfire etc)
# notifications:
#   irc: "irc.freenode.org#yourfavouriteroomfortravis"
