# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.locale_listener:
        class: Syw\Front\MainBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    app.user_locale_listener:
        class: Syw\Front\MainBundle\EventListener\UserLocaleListener
        arguments: [@session]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    syw.password_resetting:
        class: Syw\Front\MainBundle\EventListener\PasswordResettingListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    syw.form_success:
        class: Syw\Front\MainBundle\EventListener\FormSuccessListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    syw_user.registration.form.type:
        class: Syw\Front\MainBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: syw_user_registration }
    syw.util.user_manipulator:
        class:      Syw\Front\MainBundle\Util\UserManipulator
        arguments:  [@fos_user.user_manager]
    syw.userprofile_manager:
        class:      Syw\Front\MainBundle\Manager\UserProfileManager
    syw.repository_helper:
        class: Syw\Front\MainBundle\Util\RepositoryHelper
        arguments: [ @doctrine.orm.entity_manager ]
